//! Generated by scripts/sync-version.mjs — do not edit.
//! App + pinned DSH versions come from a single source (config/version.json).

/// Current dsh-platform app version.
pub const APP_VERSION: &str = "0.1.1";

/// Pinned DeepSeek Harness CLI version (install_runtime default).
pub const DSH_VERSION: &str = "0.1.1-rc.2";
