#!/usr/bin/env node
/**
 * prepare-harness — validate the DSH submodule and render overlay configs.
 *
 *  1. Verifies harness/ (submodule or mirror) and the pinned tag record.
 *  2. Ensures the DSH CLI is locatable (harness build output or npm fallback).
 *  3. Renders config/*.overlay.yml templates into *.generated.yml with
 *     absolute module specifiers the DSH loader accepts.
 *
 * The render logic mirrors packages/shared-dsh/src/patch-loader.ts (kept
 * dependency-free here so this script runs before any build step).
 *
 * Usage:
 *   node scripts/prepare-harness.mjs [--build] [--root <path>]
 */
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { load } from 'js-yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')

const PINNED_TAG = 'dsh-v0.1.0-rc.8'
const CLI_CANDIDATES = [
  join(repoRoot, 'harness', 'apps', 'cli', 'lib', 'bin.js'),
  join(repoRoot, 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js')
]

const OVERLAYS = [
  { template: 'desktop-overlay.yml', output: 'desktop-overlay.generated.yml' },
  { template: 'mobile-overlay.yml', output: 'mobile-overlay.generated.yml' },
  { template: 'harmony-overlay.yml', output: 'harmony-overlay.generated.yml' }
]

const log = (message) => console.log(`[prepare-harness] ${message}`)
const fail = (message) => {
  console.error(`[prepare-harness] ERROR: ${message}`)
  process.exitCode = 1
}

// ---- 1. submodule / CLI check ----------------------------------------------
const harness = join(repoRoot, 'harness')
if (!existsSync(join(harness, 'apps', 'cli', 'package.json'))) {
  fail(`harness/ is missing apps/cli — run 'git submodule update --init --recursive'`)
} else {
  const status = spawnSync('git', ['-C', harness, 'status', '--porcelain'], { encoding: 'utf8' })
  if (status.status === 0 && status.stdout.trim() !== '') {
    fail(`harness/ has uncommitted changes:\n${status.stdout}`)
  } else {
    const described = spawnSync('git', ['-C', harness, 'describe', '--tags', '--always'], { encoding: 'utf8' })
    const tag = described.stdout?.trim() || 'unknown'
    log(`harness verified (${tag}; pinned expectation ${PINNED_TAG} — see HARNESS_UPSTREAM.md)`)
  }
}

const cli = CLI_CANDIDATES.find((candidate) => existsSync(candidate))
if (cli) log(`DSH CLI: ${cli}`)
else fail(`no DSH CLI found (${CLI_CANDIDATES.join(', ')}) — run 'pnpm install'`)

// ---- 2. plugin build outputs ------------------------------------------------
const pluginDirs = [
  'plugins/dsh-plugins/desktop-bridge',
  'plugins/dsh-plugins/dsh-attachments',
  'plugins/dsh-plugins/dsh-session-backup',
  'plugins/dsh-plugins/dsh-market',
  'plugins/dsh-plugins/dsh-lan-access'
]
for (const dir of pluginDirs) {
  const entry = join(repoRoot, dir, 'lib', 'index.js')
  if (!existsSync(entry)) {
    log(`plugin ${dir} not built (lib/index.js missing) — run 'pnpm --filter @dsh-platform/${dir.split('/').pop()} build'`)
  }
}

// ---- 3. render overlays ------------------------------------------------------
/**
 * Resolve one plugin ref exactly like shared-dsh's patch-loader:
 *   - file: URLs / absolute paths are kept;
 *   - ./… refs resolve against the repo root, preferring built lib/index.js.
 */
function resolvePluginRef(name, options) {
  if (name.startsWith('file:') || isAbsolute(name)) return name
  if (name.startsWith('.')) {
    const abs = resolve(options.root, name)
    // The DSH loader imports row names through the ESM loader: on Windows a
    // plain absolute path arrives as a bare specifier with scheme 'e:' and
    // fails, so absolute refs must be file:// URLs.
    const toUrl = (path) => 'file:///' + path.replace(/\\/g, '/').replace(/\s/g, '%20')
    const built = join(abs, 'lib', 'index.js')
    const dist = join(abs, 'dist', 'index.js')
    if (options.preferBuilt && existsSync(built)) return toUrl(built)
    if (options.preferBuilt && existsSync(dist)) return toUrl(dist)
    return toUrl(abs)
  }
  return name
}

function renderOverlay(overlay, options) {
  return overlay.map((entry) =>
    entry?.insert
      ? { ...entry, insert: entry.insert.map((row) => (row.name ? { ...row, name: resolvePluginRef(row.name, options) } : row)) }
      : entry
  )
}

function writeOverlay(overlay, file, src) {
  const header = `# GENERATED by scripts/prepare-harness.mjs from config/${src} — do not edit.\n# Plugin refs are absolute module specifiers; re-render with 'pnpm prepare:harness'.\n`
  writeFileSync(file, header + JSON.stringify(overlay, null, 2), 'utf8')
}

for (const { template, output } of OVERLAYS) {
  const templatePath = join(repoRoot, 'config', template)
  if (!existsSync(templatePath)) {
    fail(`overlay template missing: ${templatePath}`)
    continue
  }
  const overlay = renderOverlay(load(readFileSync(templatePath, 'utf8')), {
    root: repoRoot,
    preferBuilt: true
  })
  writeOverlay(overlay, join(repoRoot, 'config', output), template)
  const count = overlay.reduce((sum, entry) => sum + (entry?.insert?.length ?? 0), 0)
  log(`rendered config/${output} (${count} inserted row(s))`)
}

log('done')
