#!/usr/bin/env node
/**
 * smoke-sidecar — end-to-end verification of the sidecar bootstrap without
 * the Tauri shell:
 *
 *   1. renders the overlay (prepare:harness equivalent)
 *   2. starts a fake native bridge listener on 127.0.0.1:9527
 *   3. spawns `node <cli> web --patch <overlay> --host 127.0.0.1 --port 0
 *      --no-open` with an isolated DSH_HOME (./.dsh-smoke/home)
 *   4. waits for `dsh web: http://127.0.0.1:<PORT>`, then hits the server
 *   5. waits until the desktop-bridge plugin's 5s status interval POSTs to
 *      the fake bridge (proves plugin rows activated)
 *   6. terminates the sidecar and reports
 *
 * Exit code 0 = sidecar READY + overlay plugins active + bridge wired.
 */
import { spawn } from 'node:child_process'
import { createServer } from 'node:http'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { load } from 'js-yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')

const READY_LINE_PREFIX = 'dsh web: http://127.0.0.1:'
const BRIDGE_PORT = 9527

const cliCandidates = [
  join(repoRoot, 'harness', 'apps', 'cli', 'lib', 'bin.js'),
  join(repoRoot, 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js')
]
const cli = cliCandidates.find((candidate) => existsSync(candidate))
if (!cli) {
  console.error(`[smoke] DSH CLI not found (${cliCandidates.join(', ')})`)
  process.exit(1)
}

// ---- render overlay ---------------------------------------------------------
const overlayTemplate = join(repoRoot, 'config', 'desktop-overlay.yml')
const generated = join(repoRoot, 'config', 'desktop-overlay.generated.yml')
const overlay = load(readFileSync(overlayTemplate, 'utf8'))
const toUrl = (path) => 'file:///' + path.replace(/\\/g, '/').replace(/\s/g, '%20')
const rendered = overlay.map((entry) =>
  entry?.insert
    ? {
        ...entry,
        insert: entry.insert.map((row) => {
          if (typeof row?.name !== 'string' || !row.name.startsWith('.')) return row
          const abs = resolve(repoRoot, row.name)
          const built = join(abs, 'lib', 'index.js')
          return { ...row, name: toUrl(existsSync(built) ? built : abs) }
        })
      }
    : entry
)
writeFileSync(
  generated,
  `# GENERATED by scripts/smoke-sidecar.mjs — do not edit.\n${JSON.stringify(rendered, null, 2)}\n`,
  'utf8'
)
console.log(`[smoke] overlay rendered → ${generated}`)

// ---- fake native bridge listener -------------------------------------------
const bridgeRequests = []
const bridgeServer = createServer((req, res) => {
  let body = ''
  req.on('data', (chunk) => (body += chunk))
  req.on('end', () => {
    bridgeRequests.push({ method: req.method, url: req.url, body })
    res.writeHead(200, {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type'
    })
    res.end(JSON.stringify({ id: 'smoke', success: true, version: 1 }))
  })
}).listen(BRIDGE_PORT, '127.0.0.1')

// ---- spawn ------------------------------------------------------------------
const dshHome = join(repoRoot, '.dsh-smoke', 'home')
mkdirSync(dshHome, { recursive: true })

const child = spawn(
  process.execPath,
  [cli, 'web', '--patch', generated, '--host', '127.0.0.1', '--port', '0', '--no-open'],
  { env: { ...process.env, DSH_HOME: dshHome }, stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true }
)

const bootLines = []
let stderr = ''
let readyUrl = null

const deadline = Date.now() + 120_000
let settled = false

function finish(code, message) {
  if (settled) return
  settled = true
  console.log(message)
  try {
    child.kill('SIGKILL')
  } catch {
    /* already gone */
  }
  bridgeServer.close()
  process.exit(code)
}

const timer = setInterval(async () => {
  if (settled) return

  const bridgeStatus = bridgeRequests
    .map((request) => `${request.method} ${request.url}`)
    .join(', ')
  const hasBridgeTraffic = bridgeRequests.length > 0

  if (readyUrl) {
    const response = await fetch(readyUrl, { signal: AbortSignal.timeout(8000) }).catch(() => null)
    // The desktop-bridge plugin reports status every 5s; give it up to 15s.
    if (hasBridgeTraffic || Date.now() - readyAt > 15_000) {
      clearInterval(timer)
      const summary = [
        `[smoke] ready = ${readyUrl} (HTTP ${response?.status ?? 'ERR'})`,
        `[smoke] bridge traffic on :${BRIDGE_PORT}: ${bridgeStatus || 'NONE (plugins inactive?)'}`,
        `[smoke] stderr tail:\n${stderr.split(/\r?\n/).slice(-30).join('\n')}`
      ]
      finish(hasBridgeTraffic ? 0 : 1, summary.join('\n'))
      return
    }
  }

  if (Date.now() > deadline) {
    clearInterval(timer)
    finish(1, `[smoke] TIMEOUT waiting for ready line.\nstderr tail:\n${stderr.split(/\r?\n/).slice(-30).join('\n')}`)
  }
  if (child.exitCode !== null) {
    clearInterval(timer)
    finish(1, `[smoke] DSH exited with code ${child.exitCode} (no ready line).\nstderr tail:\n${stderr.split(/\r?\n/).slice(-30).join('\n')}`)
  }
}, 500)

let readyAt = 0

child.stdout.setEncoding('utf8')
child.stdout.on('data', (chunk) => {
  for (const line of chunk.split(/\r?\n/)) {
    if (line.startsWith(READY_LINE_PREFIX)) {
      readyUrl = line.trim().replace(READY_LINE_PREFIX, 'http://127.0.0.1:')
      readyAt = Date.now()
      console.log(`[smoke] READY: ${readyUrl}`)
    }
    bootLines.push(line)
  }
})

child.stderr.setEncoding('utf8')
child.stderr.on('data', (chunk) => {
  stderr += chunk
})
