#!/usr/bin/env node
/**
 * sync-version — 把 config/version.json 里的单一版本来源同步到所有位置:
 *
 *   - app   → 根/各 workspace 的 package.json、各 app 的 tauri.conf.json、
 *             Cargo.toml(workspace + shared-rust)的 version 字段
 *   - dsh   → 根 package.json 的 @deepseek-ai/dsh 依赖 pin,并生成
 *             apps/desktop/src-tauri/src/version.rs(APP_VERSION / DSH_VERSION)
 *
 * 说明: 仅"就地替换"version 值,保留每份文件原有格式,避免改动内容触发
 * pnpm 对 node_modules 的整树清理。用法: node scripts/sync-version.mjs
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const { app, dsh } = JSON.parse(readFileSync(join(root, 'config', 'version.json'), 'utf8'))

const log = (message) => console.log(`[sync-version] ${message}`)

/** Walk a directory tree for `package.json`, skipping build/local dirs. */
function collectPackageJson(dir, results = []) {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === 'target' || name === 'harness' || name === '.git' || name === 'dist' || name === 'lib' || name === '.turbo' || name === '.dsh-smoke') continue
    const p = join(dir, name)
    if (statSync(p).isDirectory()) collectPackageJson(p, results)
    else if (name === 'package.json') results.push(p)
  }
  return results
}

/** In-place replace of a JSON `"version": "..."` value, preserving formatting. */
function setJsonVersion(file, value) {
  const raw = readFileSync(file, 'utf8')
  let current
  try {
    current = JSON.parse(raw).version
  } catch {
    return false
  }
  if (current === undefined || current === value) return false
  const next = raw.replace(`"version": "${current}"`, `"version": "${value}"`)
  if (next === raw) return false
  writeFileSync(file, next, 'utf8')
  return true
}

let packageCount = 0
for (const dir of ['apps', 'packages', 'plugins']) {
  for (const file of collectPackageJson(join(root, dir))) {
    if (setJsonVersion(file, app)) packageCount++
  }
}
const rootPkgFile = join(root, 'package.json')
if (existsSync(rootPkgFile)) {
  const rootPkg = JSON.parse(readFileSync(rootPkgFile, 'utf8'))
  const devDsh = rootPkg.devDependencies?.['@deepseek-ai/dsh']
  if (devDsh && devDsh !== dsh) {
    const raw = readFileSync(rootPkgFile, 'utf8')
    const next = raw.replace(`"@deepseek-ai/dsh": "${devDsh}"`, `"@deepseek-ai/dsh": "${dsh}"`)
    writeFileSync(rootPkgFile, next, 'utf8')
    log(`root @deepseek-ai/dsh -> ${dsh}`)
  }
  if (setJsonVersion(rootPkgFile, app)) packageCount++
}
log(`package.json -> ${app} (${packageCount} files)`)

let tauriCount = 0
for (const name of readdirSync(join(root, 'apps'))) {
  const conf = join(root, 'apps', name, 'src-tauri', 'tauri.conf.json')
  if (existsSync(conf) && setJsonVersion(conf, app)) tauriCount++
}
log(`tauri.conf.json -> ${app} (${tauriCount} files)`)

let cargoCount = 0
for (const cargoFile of [join(root, 'Cargo.toml'), join(root, 'packages', 'shared-rust', 'Cargo.toml')]) {
  if (!existsSync(cargoFile)) continue
  const raw = readFileSync(cargoFile, 'utf8')
  const m = raw.match(/version\s*=\s*"([^"]+)"/)
  if (m && m[1] !== app) {
    writeFileSync(cargoFile, raw.replace(m[0], `version = "${app}"`), 'utf8')
    cargoCount++
  }
}
log(`Cargo.toml -> ${app} (${cargoCount} files)`)

const versionRs = `//! Generated by scripts/sync-version.mjs — do not edit.
//! App + pinned DSH versions come from a single source (config/version.json).

/// Current dsh-platform app version.
pub const APP_VERSION: &str = "${app}";

/// Pinned DeepSeek Harness CLI version (install_runtime default).
pub const DSH_VERSION: &str = "${dsh}";
`
writeFileSync(join(root, 'apps', 'desktop', 'src-tauri', 'src', 'version.rs'), versionRs, 'utf8')
log('generated apps/desktop/src-tauri/src/version.rs')

log('done')
